on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - run: |
          docker version
          docker info
          docker build -t test-image .
          docker images -a
          docker image inspect test-image
          docker image inspect mcr.microsoft.com/windows/nanoserver:1809
          docker save -o images.tar test-image mcr.microsoft.com/windows/nanoserver:1809
          tar -xf images.tar *.json

      - uses: actions/upload-artifact@v2
        with:
          name: metadata
          path: "*.json"

      - run: docker load -i images.tar
